// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZf0wRHsqoeG5jg20uxuLBzprxnQRxbS0',
    appId: '1:304174307027:web:51b73595871515b64be626',
    messagingSenderId: '304174307027',
    projectId: 'fb-firebase-9cc19',
    authDomain: 'fb-firebase-9cc19.firebaseapp.com',
    storageBucket: 'fb-firebase-9cc19.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWdfuZdxBoz_wpjAdpzortni2Pc1cfOb8',
    appId: '1:304174307027:android:8139e16af84a62f44be626',
    messagingSenderId: '304174307027',
    projectId: 'fb-firebase-9cc19',
    storageBucket: 'fb-firebase-9cc19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrrzBqnccqAOZbuuMjucKQyB5Omn6GFgU',
    appId: '1:304174307027:ios:3816353853c18dfa4be626',
    messagingSenderId: '304174307027',
    projectId: 'fb-firebase-9cc19',
    storageBucket: 'fb-firebase-9cc19.appspot.com',
    iosClientId: '304174307027-502j66b8rgsujadp6epk40u71mu3vbut.apps.googleusercontent.com',
    iosBundleId: 'africa.victory.tech.instaVal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrrzBqnccqAOZbuuMjucKQyB5Omn6GFgU',
    appId: '1:304174307027:ios:3816353853c18dfa4be626',
    messagingSenderId: '304174307027',
    projectId: 'fb-firebase-9cc19',
    storageBucket: 'fb-firebase-9cc19.appspot.com',
    iosClientId: '304174307027-502j66b8rgsujadp6epk40u71mu3vbut.apps.googleusercontent.com',
    iosBundleId: 'africa.victory.tech.instaVal',
  );
}
